---
name: Python application

on:
  push:
    branches:
      - Victoria
      - Javon
      - Todasha
      - jin
      - tumi
      - james
  pull_request:
    branches:
      - Victoria
      - Javon
      - Todasha
      - jin
      - tumi
      - james

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Run on Ubuntu, MacOS, and Windows

    steps:
    - uses: actions/checkout@v3
    
    # Set up Python 3.x
    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Lint with flake8
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    # Run unit tests with unittest (specifically test.py)
    - name: Run unit tests with unittest
      run: |
        python -m unittest test.py  # Run the specific test file "test.py"
    
    # Optionally, run pytest for all other tests (if needed)
    - name: Test with pytest
      run: |
        pytest
