---
name: Run Unit Tests For Mac with all push

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - Victoria
      - Javon
      - Todasha
      - jin
      - tumi
      - james
  workflow_dispatch:
jobs:
  test:
    runs-on: macos-latest
    
    steps:
      # Step 1: Checkout the repository codes
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Step 4: Run the old unit tests (main)
      - name: Run old version unit tests on main
        run: |
          python -m unittest test.py
