name: Run Unit Tests For All Separate Branches

on:
  push:
    branches:
      - Victoria
      - Javon
      - Todasha
      - jin
      - tumi
      - james
  pull_request:
    branches:
      - Victoria
      - Javon
      - Todasha
      - jin
      - tumi
      - james

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    # Matrix configuration to run tests on multiple OS (Ubuntu, MacOS, Windows)
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Step 4: Run the unit tests
      - name: Run unit tests
        run: |
          python -m unittest test.py
