---
name: Run Unit Tests For Ubuntu with all push

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - Victoria
      - Javon
      - Todasha
      - jin
      - tumi
      - james

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libfreetype6-dev libportmidi-dev libjpeg-dev python3-setuptools python3-dev
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install sphinx numpy>=1.21.0 "Cython>=3.0,<3.1"

      - name: Set environment variables for audio and video
        run: |
          echo "SDL_VIDEODRIVER=dummy" >> $GITHUB_ENV
          echo "SDL_AUDIODRIVER=disk" >> $GITHUB_ENV
          
      - name: Run unit tests
        run: |
          python -m unittest test.py
